# Generated by Django 2.2.7 on 2020-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('dis_price', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
    ]
