# Generated by Django 2.2.7 on 2020-08-12 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('contact_verify', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('email_verify', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=50)),
                ('transacton_id', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.user_basics')),
            ],
        ),
    ]
