# Generated by Django 2.2.7 on 2020-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(default='1234', max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
                ('contact', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
